// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYlB_zwRqRHcM5uHk_IkeS7y0pi6NEJhM',
    appId: '1:196295159582:web:52f238efd0537d3cb1a30f',
    messagingSenderId: '196295159582',
    projectId: 'evird-htiw-erehps',
    authDomain: 'evird-htiw-erehps.firebaseapp.com',
    storageBucket: 'evird-htiw-erehps.firebasestorage.app',
    measurementId: 'G-JXXKMYFBKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByeZ39kdI600kB003wXAlL3rYad_Qbu4',
    appId: '1:196295159582:android:10e12c6f9781926db1a30f',
    messagingSenderId: '196295159582',
    projectId: 'evird-htiw-erehps',
    storageBucket: 'evird-htiw-erehps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlxMS0dXHVGla5DXH3aR59c22-bdEkLs',
    appId: '1:196295159582:ios:ceab4f103cc75e50b1a30f',
    messagingSenderId: '196295159582',
    projectId: 'evird-htiw-erehps',
    storageBucket: 'evird-htiw-erehps.firebasestorage.app',
    iosBundleId: 'evird-htiw-erehps.sphereWithDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ZL5ed4WARLwI7ENMKrdHroMCJEWcXPk',
    appId: '1:541870879845:ios:58df0cbc3382414770828c',
    messagingSenderId: '541870879845',
    projectId: 'sphare-3fd0c',
    storageBucket: 'sphare-3fd0c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYlB_zwRqRHcM5uHk_IkeS7y0pi6NEJhM',
    appId: '1:196295159582:web:f7aed88742129832b1a30f',
    messagingSenderId: '196295159582',
    projectId: 'evird-htiw-erehps',
    authDomain: 'evird-htiw-erehps.firebaseapp.com',
    storageBucket: 'evird-htiw-erehps.firebasestorage.app',
    measurementId: 'G-B6HFJKYQ7G',
  );

}